version: "3.7"

services:

  jaeger:
    image: quay.io/jaegertracing/all-in-one:latest
    restart: always
    environment:
      LOG_LEVEL: debug
      COLLECTOR_OTLP_ENABLED: 'true'
    ports:
      - "${JARGER_WEBUI_PORT:-16686}:16686"
      - "${OTLP_EXPORTER_PORT:-4317}:4317"

  backend:
    restart: on-failure:5 
    build:
      context: ./src/backend
      args:
        IMAGE_VERSION: ${VERSION}
    image: oci.local/${PROJECT_NAMESPACE}/${PROJECT_NAME}/backend:${VERSION}
    # command: tail -f /dev/null
    # command: hypercorn --bind 0.0.0.0:8001 asgi:app --reload
    ports:
      - "48180:8000"
    environment:
      TZ: Canada/Montreal
      # OTLP GRPC
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4317}
      OTEL_EXPORTER_OTLP_INSECURE: ${OTEL_EXPORTER_OTLP_INSECURE:-true}
      # Sqlite
      DATABASE_ENGINE: "sqlite"
    links:
      - jaeger
    # volumes:
    #   - ./src/backend/src:/usr/local/app/src

  frontend:
    restart: on-failure:5 
    build:
      context: ./src/frontend
      args:
        IMAGE_VERSION: ${VERSION}
    image: oci.local/${PROJECT_NAMESPACE}/${PROJECT_NAME}/frontend:${VERSION}
    # command: tail -f /dev/null
    # command: hypercorn --bind 0.0.0.0:8000 asgi:app --reload
    ports:
      - "48080:8000"
    environment:
      BACKEND_API_URL: http://backend:8000
      TZ: Canada/Montreal
      # OTLP GRPC
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4317}
      OTEL_EXPORTER_OTLP_INSECURE: ${OTEL_EXPORTER_OTLP_INSECURE:-true}
    links:
      - backend
      - jaeger
    volumes:
      - ./src/frontend/src:/usr/local/app/src
