{{- $serviceMonitor := .Values.frontend.serviceMonitor -}}
{{- $port := .Values.frontend.service.port -}}
{{- if $serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chart.fullname" . }}-frontend
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    {{- with .Values.frontend.extraLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if $serviceMonitor.labels }}
      {{- toYaml $serviceMonitor.labels | nindent 4 }}
    {{- end }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if $serviceMonitor.annotations }}
  annotations:
    {{- toYaml $serviceMonitor.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- with .Values.backend.extraLabels }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
  namespaceSelector:
    {{- if $serviceMonitor.namespaced }}
    matchNames:
      - {{ .Release.Namespace }}
    {{- else }}
    any: true
    {{- end }}
  endpoints:
  - port: {{ $port | quote }}
    path: /metrics
    {{- if $serviceMonitor.interval }}
    interval: {{ $serviceMonitor.interval }}
    {{- end }}
    {{- if $serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ $serviceMonitor.scrapeTimeout }}
    {{- end }}
{{- end }}
