---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fakenames-db
  description: PostgreSQL database populated from https://fakenames.org dataset
  # annotations:
  #   backstage.io/kubernetes-id: fastapi-demo
spec:
  type: database
  owner: "testruction.io"
  system: fastapi-demo
tags:
  - postgres
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: fakenames
  description: Fake identity provider
  tags:
    - rest
    - fastapi
    - python3
  annotations:
    backstage.io/kubernetes-id: backend
    backstage.io/kubernetes-namespace: fastapi-demo
  # annotations:
  #   # The annotation is deprecated, we use placeholders (see below) instead, remove it later.
  #   backstage.io/definition-at-location: 'url:https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/spotify.com/v1/swagger.yaml'
spec:
  type: openapi
  lifecycle: production
  owner: "testruction.io"
  system: fastapi-demo
  definition:
    $text: https://github.com/testruction/fastapi-sqlalchemy-cockroachdb/blob/main/specs/openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend
  description: FastApi backend API demonstration
  tags:
    - fastapi
    - dash
    - python3
    - ui
  annotations:
    backstage.io/kubernetes-id: backend
    backstage.io/kubernetes-namespace: fastapi-demo
  links:
    - url: http://localhost/v1/docs
      title: Api documentation
      icon: docs
      type: apidocs
spec:
  type: service
  lifecycle: production
  owner: "testruction.io"
  system: fastapi-demo
  dependsOn:
    - resource:fakenames-db
  providesApis:
    - fakenames
