---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
  description: FastApi and Dash frontend demonstration
  tags:
    - fastapi
    - dash
    - python3
    - ui
  annotations:
    github.com/project-slug: testruction/fastapi-sqlalchemy-cockroachdb
    backstage.io/kubernetes-id: frontend
    backstage.io/kubernetes-namespace: fastapi-demo
  links:
    - url: http://localhost
      title: Home page
      icon: home
      type: admin-dashboard
    - url: https://metrics.example-org.com
      title: metrics
      icon: analytics
      type: metrics-dashboard
    - url: https://logs.example-org.com
      title: logs
      icon: assignment
      type: logs-dashboard
spec:
  type: service
  lifecycle: production
  owner: "testruction.io"
  system: fastapi-demo
  consumesApis:
    - api:fakenames
  dependsOn:
    - component:backend